GET http://localhost:4000/dashboard

###

GET http://localhost:4000/dashboard/5df2ec63a2a03352f09ac607

###

POST http://localhost:4000/dashboard
Content-Type: application/json

{
    "symbol": "SPSY",
    "name": "Sample Post Symbol",
    "price_open": "123",
    "day_high": "123",
    "day_low": "123",
    "close_yesterday": "123",
    "volume": "123"
} 

###

DELETE http://localhost:4000/dashboard/5df2ec4a6ba8f952b7ed41fd

###

PATCH http://localhost:4000/dashboard/5df2ebc601f11e51dffed77e
Content-Type: application/json

{
    "symbol": "SPSY",
    "name": "Sample PATCH Symbol",
    "price_open": "123",
    "day_high": "123",
    "day_low": "123",
    "close_yesterday": "123",
    "volume": "123"
} 
