GET http://localhost:4000/dashboard/symbol

###

GET http://localhost:4000/dashboard/symbol/5df3e1405d7d141ef0821473

###

POST http://localhost:4000/dashboard/symbol
Content-Type: application/json

{
    "symbol": "SPSY",
    "name": "Sample Post Symbol",
    "price_open": "123",
    "day_high": "123",
    "day_low": "123",
    "close_yesterday": "123",
    "volume": "123"
} 

###

DELETE http://localhost:4000/dashboard/symbol/5df2ec4a6ba8f952b7ed41fd

###

PATCH http://localhost:4000/dashboard/symbol/5df2ebc601f11e51dffed77e
Content-Type: application/json

{
    "symbol": "SPSY",
    "name": "Sample PATCH Symbol",
    "price_open": "123",
    "day_high": "123",
    "day_low": "123",
    "close_yesterday": "123",
    "volume": "123"
} 
