import { STRING_CONSTANTS } from 'shared/constants/stringConstants';

export const WATCHLIST_TABLE_NAME = STRING_CONSTANTS.TABLE.NAME;
export const COLUMN_HEADERS = STRING_CONSTANTS.TABLE.COLUMN_HEADERS;

export const BUTTONS = STRING_CONSTANTS.BUTTONS;

export const QUOTE_DETAIL_HEADER = STRING_CONSTANTS.QUOTE_DETAIL.HEADER;
export const QUOTE_DETAIL_BUTTONS = STRING_CONSTANTS.QUOTE_DETAIL.BUTTONS;